
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --requirepass secretpass
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
